--- # EC2 - Start/stop/terminate moduel example
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
 
  - files/awscreds.yml
  tasks:
  - name: manage the state of an instance
    ec2:
    aws_access_key: "{{ aws_id }}"
    aws_secret_key: "{{ aws_key }}"
    region: "{{ aws_region }}"
    instance_ids: i-01f35bb8f37080108
    state: running
